### ISSUE TITLE
What is the meaning of "languages"?

### ISSUE THREAD

**Issue by jesusfj710** [ihucos/counter.dev#122]
On the dashboard in the languages section I am able to see English and Spanish, although my website is also available in Korean and the actions I do there are not reflected.

However, in "Pageviews" they do register.

<img width="372" alt="image" src="https://github.com/ihucos/counter.dev/assets/71794881/c06aa654-f6a3-43ad-8ea8-be1d53ef79bb">

How exactly does this metric work or how is it collected?

<img width="486" alt="image" src="https://github.com/ihucos/counter.dev/assets/71794881/2617fc53-0428-41e3-8925-478596b4d822">

**Comment by ihucos** [comment]
Hello jesusfj710,

those are two different metrics.

- "Languages" is the end-users language selected in the browser setting.
- "Pageviews" in this specific cases reflects which language the user is accessing in your website.

It is possible that users have their browsers language setting set to Spanish but are accessing the Korean version of your website. One completely made up scenario would be a person which likes to browse in Korean which is traveling trough Spain and accesses Computers where Spanish is set as main language.

So "Languages" is more or less "The browsers preferred language" not sure if the label could be improved.

Cheers
