### ISSUE TITLE
Use your own profile by default rather than stock profile

### ISSUE THREAD

**Issue by mousetail** [ihucos/counter.dev#14]
The standard javascript you need to copy-paste has a hardcoded account name that makes your data public. It might be nicer to automatically fill in the users own username, or include some text to say that you should substitute your own username instead of the pre-filled value.

Also, the script preview is blocked by my ad blocker. I don't really mind not tracking users with add blockers, though I would prefer if the admin screen settings page worked.

**Comment by ihucos** [comment]
Hello Mousetail,

thank you very much for the issue. Will look into it. Sorry for the late reply, I had some short term stress on my current for-money-job. Will try to address is this weekend.

That will be just like a super hotfix, we are currently working on a redesign, see this mockup as example: https://github.com/ihucos/counter.dev/blob/master/mockups/graphs.svg

Cheers!

**Comment by mousetail** [comment]
Thank you for replying. Would be great if you fixed this but there is no rush.

The new design looks great!

**Comment by ihucos** [comment]
It is fixed :-D new design and everything: [counter.dev](counter.dev)

Thanks for the issue.
