### ISSUE TITLE
Support for projects

### ISSUE THREAD

**Issue by jcubic** [ihucos/counter.dev#23]
Does your service support projects? I was looking at the  tracking code and it looks that it's not. I would be good idea to add projects with Id, where users can set different projects with different IDs and show statistics for different projects.

It support domains but I would like to have same project for different domains? For instance I would be able to track the usage of bookmarklet for my Open source project.

**Comment by ihucos** [comment]
Interesting idea. Will leave it open but don't hold your breath on this.

**Comment by ihucos** [comment]
Will close and see if it resurfaces.
