### ISSUE TITLE
Page views for single user

### ISSUE THREAD

**Issue by jcubic** [ihucos/counter.dev#24]
It would be nice if the tracking was counting more the one visit, it's not very useful if you want to know if someone would open main website and click on for instance documentation page.

If think it's good idea to send tracking code once for first visit and send smaller ajax requests on each visited page. If the tracking is per sessionStorage it will give single session on the website what pages he visited.

**Comment by jcubic** [comment]
I see that you advertise your project as "Shows how many people visit your web application." but I would like to use for html based static website I want to know what html pages the users visits. Is this something you would like to have?

**Comment by ihucos** [comment]
Got it. I am afraid counter will stay with only counting unique visits. It's a core design decision. The reasoning behind this is to have less load on the analytics server. We also focus only on the core metrics.
