### ISSUE TITLE
Donation don't work

### ISSUE THREAD

**Issue by jcubic** [ihucos/counter.dev#25]
I just wanted to donate and the paypal button don't work. Looks like error in PayPal you should report this.
This is the error in console
```
assertion.js:64 Uncaught TypeError: Parameter `currency.value` must be a number or a string representing a canonical number (e.g, `"9999.99"`), not string `"20,00"`
    at u (assertion.js:64)
    at c (assertion.js:118)
    at assertCanonicalNumberType (numberHelpers.js:34)
    at h.value [as formatCurrency] (number.js:238)
    at y (formator.js:114)
    at Object../utility/getTemplateData.js (getTemplateData.js:71)
    at n (bootstrap:19)
    at Module../routes/member.js (member.js:4177)
    at n (bootstrap:19)
    at bootstrap:83
```

which is stupid because you can't type 20.00 only 20,00 that is not valid according to assertion.js. Maybe the issue with localization some countries use `,` (like Poland) some `.` (USA).

**Comment by ihucos** [comment]
Thanks! That is weird, especially that paypal throws an js exception. I regenerated and changed the code. The code used previously has `&locale.x=en_DE` in it, maybe it's related to this.

**Comment by ihucos** [comment]
Reopen if it persists. Thanks for proving a pay as you want monetization model can work ;-)

**Comment by jcubic** [comment]
Unfortunately there is still an error. Maybe you should report this to PayPal.

**Comment by jcubic** [comment]
No sorry, it works I was using same link because didn't refreshed the website. One thing the transaction fee checkbox disappeared (I think it was about ~0,85).
