### ISSUE TITLE
whitelist domains

### ISSUE THREAD

**Issue by ihucos** [ihucos/counter.dev#33]
only allow user given domains to be added.
A very common feature request.

**Comment by noraj** [comment]
Requested by email: (give a little more context)

> 
> I remember Google Analytics has a simple security feature where you can declare authorized hosts from your dashboard (whitelist).
> 
> Else since anyone can add the snippet on it's own website (with your username )and start polluting your dashboard.
> 
> Would be nice to have that. 

> To complete my previous message:
> 
>    - I know you can remove a site from the WebUI
>    - Preview and CI/CD pipeline are automatically registering new hosts during deployment so for example with netlify I will have a different new host commit--sitename.netlify.app at each commit and it will give me tons of manually work to remove all unwanted hosts from my counter analytics dashboard each time. This is to give a non malicious example. So it's not only a security feature but also a convenient one.

**Comment by ihucos** [comment]
Closing as it's implemented - it's in the user settings.
