### ISSUE TITLE
customizable time frame (interval)

### ISSUE THREAD

**Issue by noraj** [ihucos/counter.dev#34]
Would it be possible to have a customizable time frame (interval) on the dashboard?

![image](https://user-images.githubusercontent.com/16578570/120531040-75b6c380-c3de-11eb-9f30-f8afa4947f6e.png)

instead of

![image](https://user-images.githubusercontent.com/16578570/120530492-ddb8da00-c3dd-11eb-939b-d42d43d76188.png)

**Comment by ihucos** [comment]
It would be possible. But it is non-trivial to make this in a way that is sustainable with the product being donation based. So this is a little a business development question and an ongoing thing. Essentially you would have to pay for this feature as it would need a "normal" sql database and has higher service costs. Any feedback, comments, question, thoughts very welcome :-)

**Comment by ihucos** [comment]
So... yeah, there is some elaborate scheme of backing up the in memory redis database to a sqlite database that is light on resources and fits the whole "free" approach.

Looking into date pickers... this one looks good: https://github.com/dangrossman/daterangepicker

**Comment by noraj** [comment]
If saving the data per day is to much storage (x365 per year) to be free-tier sustainable, then we could go with saving the data per week (x52 per year), if it is still too much then per month (x12 per year) and at the very least per year (x1 per year).
So we could keep the temporary data (today, yesterday, this week, this month, this year) as well as permanent data (all range, + custom range on a per day/week/month/year basis).

If you want to know, my screenshot of a date picker was with [bulma-calendar](https://bulma-calendar.onrender.com/) extension ([demo](https://bulma-calendar.onrender.com/demonstration/date)).

**Comment by ihucos** [comment]
Thanks, yes I will need to do something like this. Now with one week of data the database is already 100 megabyte. Maybe the first weeks can be on a day to day base and then later it moves to weekly data and later maybe even to monthly as you say.

For the date picker would be nice for something that supports preselections of "Last 30 days" and so on.

**Comment by ihucos** [comment]
Done ;-)

That was a difficult one. Maybe there is a bug or two. Currently you can't select today or yesterday because it takes tiiimeee to save the data in the hard drive. But it's there in the redis server and available in the front end. I just need to merge it yadda yadda, you're welcome :-)

**Comment by noraj** [comment]
Thanks, I'll have to try that :)
