### ISSUE TITLE
Private user names

### ISSUE THREAD

**Issue by ihucos** [ihucos/counter.dev#53]
Quote

>Hello,
>
>I like your product, but I do feel like having your email displayed openly in the code of the website for this to work is.. questionable. Enough so that I might stop using it, or at the least setup a dummy email for the account.
>
>Thank you!

**Comment by woodcock3** [comment]
I agree the username should be private. But also note your username does not need to be your email address

**Comment by ihucos** [comment]
Implemented, deployed and testing: https://github.com/ihucos/counter.dev/commit/355a9fcde215097334e18fc89559a7e77147ab72

Let's see

**Comment by ihucos** [comment]
It's done, example:

```
<script >
    if (!sessionStorage.getItem("_swa") && document.referrer.indexOf(location.protocol + "//" + location.host) !== 0) {
        fetch("https://counter.dev/track?" + new URLSearchParams({
            referrer: document.referrer,
            screen: screen.width + "x" + screen.height,
            id: "33671ad4-a966-4a52-b48f-56c92d10a678",
            utcoffset: "1"
        }))
    };
sessionStorage.setItem("_swa", "1"); 
< /script>

Thanks for the ticket!
