### ISSUE TITLE
Identifies Microsoft Edge (Chromium) as IE

### ISSUE THREAD

**Issue by hello-smile6** [ihucos/counter.dev#58]
![image](https://user-images.githubusercontent.com/73048226/155861263-ef5ac96f-98f6-4756-9ffd-a0dd1f98ac8b.png)

**Comment by onodera-punpun** [comment]
Related issue: https://github.com/avct/uasurfer/pull/69

Might be time to switch to a different user agent parser?

**Comment by onodera-punpun** [comment]
It seems MacOS is also not detected. https://github.com/ihucos/counter.dev/issues/56 is most likely related as well.

**Comment by ihucos** [comment]
Sounds reasonable. Will close until it resurfaces.

**Comment by stevennyman** [comment]
I still see Microsoft Edge being detected as IE.

**Comment by ihucos** [comment]
Will fix :-)

**Comment by ihucos** [comment]
I changed the lib to the more maintained fork:  https://github.com/xavivars/uasurfer

Edge is being recognized as Edge now.
Android is still shown as linux though :-/

**Comment by ihucos** [comment]
> Android is still shown as linux though :-/

Might be related to my code, investigating :-)

**Comment by ihucos** [comment]
Identified lasting issue, fixing :-)

**Comment by ihucos** [comment]
> Identified lasting issue, fixing :-)

That pie chart is being called "Platforms", which by uasurfers defintion is:

```
const (
	PlatformUnknown Platform = iota
	PlatformWindows
	PlatformMac
	PlatformLinux
	PlatformiPad
	PlatformiPhone
	PlatformiPod
	PlatformBlackberry
	PlatformWindowsPhone
	PlatformPlaystation
	PlatformXbox
	PlatformNintendo
	PlatformBot
)
```
Note, how there is not "Android". Then there is also "OS", which is currently not being tracked. It's one of.

```
const (
	OSUnknown OSName = iota
	OSWindowsPhone
	OSWindows
	OSMacOSX
	OSiOS
	OSAndroid
	OSBlackberry
	OSChromeOS
	OSKindle
	OSWebOS
	OSLinux
	OSPlaystation
	OSXbox
	OSNintendo
	OSBot
)
```

There's "iOS" and "iPad" there which seems handy.

There are many way to fix that. 

1. Start tracking uasurfers OSes. Show a pie chart named "OS" rather then "Platform" only when this new data is available (Will never for older intregrations when vieweing all data in the dashboard)

2. Hack the "Android" into it. Making historic data slight inacurate as, as "Linux" will represent older "Android" counts.

Maybe there are also other solutions?

**Comment by ihucos** [comment]
I went with solution 1.

<img width="585" alt="Screenshot 2022-09-17 at 16 33 01" src="https://user-images.githubusercontent.com/2066372/190862277-c10ea6ea-e6e9-44a6-b834-2388afa97f4e.png">

Thanks for the feedback. I'll close the issue. Let me know if it works as expected.

**Comment by stevennyman** [comment]
Edge is now tracked correctly, thank you for fixing this so quickly!

**Comment by ihucos** [comment]
+1
