### ISSUE TITLE
The "week" view of the dashboard shows a 24 hour view

### ISSUE THREAD

**Issue by trosel** [ihucos/counter.dev#66]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/1299322/166295818-e37e3110-20c2-4416-a520-ceb08ed2f2f8.png">

Not sure what's going on. Maybe the `onTimeRangeChanged()` function is not working right

**Comment by ihucos** [comment]
On which time zone are you? If you are on a monday your week only consists of hours ;-) I think

**Comment by trosel** [comment]
@ihucos Is there no view that shows the last 7 days?

this seems like a case of a poorly written user story. when someone wants to see a week view, they want to see a sliding window of the last 7 days. 

otherwise, they can only check the week view on sunday at 11pm??

**Comment by ihucos** [comment]
I agree that last 7 days would be better. This comes trough the UI following technical constraints in order to make the product free :-D But we're working on it. At least there is a solution on the horizon. It's something on the list.

**Comment by ihucos** [comment]
We have to closely watch how much money we get trough the current donation based monetization strategy and how we can cover hosting costs with that in a sustainable day.

**Comment by ihucos** [comment]
Steps to fixing it in that ticket:  https://github.com/ihucos/counter.dev/issues/76
