### ISSUE TITLE
Group referrers (e.G. google.nl, google.de)

### ISSUE THREAD

**Issue by ihucos** [ihucos/counter.dev#75]
Straight from twitter: https://twitter.com/notifications

> [@DevCounter](https://twitter.com/DevCounter)
 Here's a thought -- some of the sources in my sources list are broken down in funny ways. Like... [http://google.com](https://t.co/h2qjP39htQ), [http://google.nl](https://t.co/sJUicxO3wR), [http://google.de](https://t.co/3eS65w83jW)... Is there any way to group like sources together? At least subdomains?

**Comment by ihucos** [comment]
implamanted

**Comment by DanHakimi** [comment]
Nice! Thank you!

I still notice a few that could be wrapped together:

com.google.android.googlequicksearchbox/ into Google Search

out.reddit.com, new.reddit.com and old.reddit.com into Reddit.

com.pinterest into Pinterest.

mobile.twitter.come into Twitter.

**Comment by ihucos** [comment]
thanks, I'll take a look later.

This can be relatively easily configured here: https://github.com/ihucos/counter.dev/blob/master/static/components/dashboard/sources-countries.js#L7

**Comment by DanHakimi** [comment]
I made a commit... I think... idk, I tried doing it in Github's UI but I can't tell if it went through.

**Comment by ihucos** [comment]
Hello DanHakimi.

Thanks, that is nice. No, I do not see a pull request in the counter github project and your fork does not contain commits I can find.

What you could do though is to send the diff of your code changes here in this github issue. That would actually be quite helpfull. Your name won't be protocolled in the git history though.

Have a nice one

Irae

**Comment by ihucos** [comment]
It's implemented
